/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  elinuxaiSidebar: [{type: 'autogenerated', dirName: 'ELinuxAIBase'}],
  calsspartoneSidebar: [{type: 'autogenerated', dirName: 'CanaanK510'}],
  canmvV1Sidebar: [
    {type: 'doc', id: 'CanaanK230-Boards/CanMV_V1/index'},
    {type: 'autogenerated', dirName: 'CanaanK230', customProps: {board: 'CanMV_V1'}},
  ],
  canmvV2Sidebar: [
    {type: 'doc', id: 'CanaanK230-Boards/CanMV_V2/index'},
    {type: 'autogenerated', dirName: 'CanaanK230', customProps: {board: 'CanMV_V2'}},
  ],
  canmvV3Sidebar: [
    {type: 'doc', id: 'CanaanK230-Boards/CANMV_V3/index'},
    {type: 'autogenerated', dirName: 'CanaanK230', customProps: {board: 'CanMV_V3'}},
  ],
  aimaixSidebar: [
    {type: 'doc', id: 'CanaanK230-Boards/AIMaix/index'},
    {type: 'autogenerated', dirName: 'CanaanK230', customProps: {board: 'AIMaix'}},
  ],
  canmvEvbSidebar: [
    {type: 'doc', id: 'CanaanK230-Boards/CANMV_EVB/index'},
    {type: 'autogenerated', dirName: 'CanaanK230', customProps: {board: 'CanMV_EVB'}},
  ],
  // 隐藏侧边栏：仅用于公共文档的 docId→sidebar 回退解析
  // 不放在导航栏下拉中，避免公共文档跳到某个具体板卡
  _sharedSidebar: [{type: 'autogenerated', dirName: 'CanaanK230'}],
};

export default sidebars;
